### ISSUE TITLE
FF crashes during SaveAsFilename installation, manual or automatic

### ISSUE THREAD

**Issue by dumbasster** [gavinsharp/SaveAsFilename#2]
Firefox 28.0 crashes when attempting to install SaveAsFilename 0.1.1-signed.
scenarios:
1. have SAF 0.1 installed, FF attempts to auto-update to 0.1.1-signed, crash (leads to browser crash every few minutes unless auto-update is turned off)
2. attempt to install 0.1.1-signed manually from AMO, GitHub, or local XPI, crash
3. delete META-INF directory from local XPI, install, no crash

**Comment by dumbasster** [comment]
Correction:  Since GitHUb only has 0.1, I was only trying to update from AMO and a local copy in scenario 2.  Thanks.

**Comment by gavinsharp** [comment]
Thanks for reporting this - this is a general issue with AMO's signing of add-ons and is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1158467.
